[proxies]
# 2025.11.19 更新说明：
# 支持vless/trojan/vmess/shadowsocks+ws的订阅生成，tls是否开启看具体节点而论，这次没有更改；
# vless/trojan/vmess+xhttp，只能是target=v2ray => xray的v2rayN使用！singbox和mihomo内核不支持xhttp协议的使用
# 小技巧：想要xhttp的，就在对应的节点配置后面添加network = "xhttp"和mode = "stream-one"字段即可，ws的保持原来的样子

# trojan+ws
[[proxies.trojan]]
remarks_prefix = "①"
password = "5be5de1d-8653-4ce3-a600-2ca1af75bdb5"
host = "trojan1.username.workers.dev"
server_name = "trojan1.username.workers.dev"
path = "/"
random_ports = [80, 8080, 8880, 2052, 2082, 2086, 2095]  # 跟非tls的端口要保持一致
network = "ws"                                           # 内部默认是 ws 也就是 websocket 协议的，可以省略，mode字段也可以省略
mode = ""

# trojan+ws+tls
[[proxies.trojan]]
remarks_prefix = "②"
password = "0195bf7c-d0d6-72ad-85c7-7a74e7db64f3"
host = "trojan2.pages.dev"
server_name = "trojan2.pages.dev"
path = "/"
random_ports = [443, 2053, 2083, 2087, 2096, 8443]       # 跟tls的端口要保持一致

# trojan+xhttp+tls
[[proxies.trojan]]
remarks_prefix = "③"
password = "0195bf7c-d0d6-72ad-85c7-7a74e7db64f3"
host = "trojan-xhttp.pages.dev"
server_name = "trojan-xhttp.pages.dev"
path = "/"
random_ports = [443, 2053, 2083, 2087, 2096, 8443]       # 跟tls的端口要保持一致
network = "xhttp"
mode = "stream-one"

# ——————————————————————————————————————————————————————————————————

# vless+ws
[[proxies.vless]]
remarks_prefix = "④"
uuid = "0195bf7c-f8c6-7add-aa36-a2145cc38ebb"
host = "vless1.username.workers.dev"
server_name = "vless1.username.workers.dev"
path = "/?ed=2048"
random_ports = [80, 8080, 8880, 2052, 2082, 2086, 2095]  # 跟非tls的端口要保持一致
network = "ws"                                           # 内部默认是 ws 也就是 websocket 协议的，可以省略，mode字段也可以省略
mode = ""

# vless+ws+tls
[[proxies.vless]]
remarks_prefix = "⑤"
uuid = "0195bf7d-17d6-704c-bd6b-fa56710382cc"
host = "vless2.pages.dev"
server_name = "vless2.pages.dev"
path = "/?ed=2048"
random_ports = [443, 2053, 2083, 2087, 2096, 8443]      # 跟tls的端口要保持一致

# vless+xhttp+tls
[[proxies.vless]]
remarks_prefix = "⑥"
uuid = "0195bf7d-17d6-704c-bd6b-fa56710382cc"
host = "vless-xhttp.pages.dev"
server_name = "vless-xhttp.pages.dev"
path = "/?ed=2048"
random_ports = [443, 2053, 2083, 2087, 2096, 8443]      # 跟tls的端口要保持一致
network = "xhttp"
mode = "stream-one"

# ——————————————————————————————————————————————————————————————————

# shadowsocks+v2ray-plugin+websocket+NTLS
[[proxies.ss]]
remarks_prefix = "⑦"
password = "none"                                       # 默认为none，不用管它，设置任何值都无效的
host = "ss1.username.workers.dev"                                
path = "/192.168.1.1-443"          
tls = false                                             # tls = false 意思使用[80, 8080, 8880, 2052, 2082, 2086, 2095]的端口
random_ports = [80, 8080, 8880, 2052, 2082, 2086, 2095] # 跟非tls的端口要保持一致

# shadowsocks+v2ray-plugin+websocket+TLS
[[proxies.ss]]
remarks_prefix = "⑧"
password = "none"                                       # 默认为none，不用管它，设置任何值都无效的
host = "ss2.pages.dev"                                  
path = "/192.168.1.1-443"                             
tls = true                                              # tls = true 意思使用[443, 2053, 2083, 2087, 2096, 8443]的端口
random_ports = [443, 2053, 2083, 2087, 2096, 8443]      # 跟tls的端口要保持一致

# xhttp，目前只支持xray内核的v2rayN、v2rayNG客户端使用，shadowsocks生成的节点分享链接只能服务于 nekoray（singbox内核）的客户端使用，无法导入v2rayN、v2rayNG客户端使用
# shadowsocks协议的，不管有没有实现服务端的xhttp，还是已经实现ws的，想在xrayN、v2rayNG客户端使用，只能手动添加，不能批量生成分享链接导入使用；xray的json配置文件，研究不深，貌似只能写一个节点在JSON配置的。

# ——————————————————————————————————————————————————————————————————

# vmess+zero+ws
[[proxies.vmess]]
remarks_prefix = "⑨"
uuid = "0195bf7c-f8c6-7add-aa36-a2145cc38ebb"
host = "vmess.xxxxx.com"                                # 自动判端host域名是否为wokers.dev而开启或关闭tls
server_name = "vmess.xxxxx.com"
path = "/"
random_ports = [443, 2053, 2083, 2087, 2096, 8443]      # 非wokers.dev域名，就跟tls的端口要保持一致

# vmess+zero+xhttp+tls（服务端没有实现，无法使用，暂时实现支持生成它的订阅，可以删除它）
[[proxies.vmess]]
remarks_prefix = "⑩"
uuid = "0195bf7c-f8c6-7add-aa36-a2145cc38ebb"
host = "vmess-xhttp.xxxxx.com"                          # 自动判端host域名是否为wokers.dev而开启或关闭tls
server_name = "vmess-xhttp.xxxxx.com"
path = "/"
random_ports = [443, 2053, 2083, 2087, 2096, 8443]      # 非wokers.dev域名，就跟tls的端口要保持一致
network = "xhttp"
mode = "stream-one"

# ——————————————————————————————————————————————————————————————————

# 后面可以继续添加
# 推荐：使用trojan、vless、ss-v2ray、vmess顺序排序，可以在url中，传入id=1参数来定位，使用哪个配置
# 注意：
#   1、这里配置的random_ports，如果配置不对，可能强制使用这里的端口，导致以为代码选择不对的端口，自我怀疑
#   2、导入v2rayN、NekoBox客户端使用，预计不使用tls模式的，结果发现wokers.dev启用tls模式，应该是代理软件问题，自动开启TLS模式（不保证百分百准确）
#   3、前面的配置，选择性使用，你有对应的节点才添加