[proxies]

# trojan+ws
# [[proxies.trojan]]
# remarks_prefix = "①"
# password = "5be5de1d-8653-4ce3-a600-2ca1af75bdb5"
# host = "trojan1.username.workers.dev"
# server_name = "trojan1.username.workers.dev"
# path = "/"
# # random_ports = [80, 8080, 8880, 2052, 2082, 2086, 2095]  # 跟非tls的端口要保持一致
# network = "ws"                                             # 主要用于指定 ws（默认） 和 xhttp 两个底层传输协议类型
# mode = ""                                                  # xhttp专用

# trojan+ws+tls
[[proxies.trojan]]
remarks_prefix = "②"
password = "0195bf7c-d0d6-72ad-85c7-7a74e7db64f3"
host = "trojan2.pages.dev"
server_name = "trojan2.pages.dev"
path = "/"
# random_ports = [443, 2053, 2083, 2087, 2096, 8443]
network = "ws"
mode = ""

# trojan+xhttp+tls
[[proxies.trojan]]
remarks_prefix = "③"
password = "0195bf7c-d0d6-72ad-85c7-7a74e7db64f3"
host = "trojan-xhttp.pages.dev"
server_name = "trojan-xhttp.pages.dev"
path = "/"
# random_ports = [443, 2053, 2083, 2087, 2096, 8443]
network = "xhttp"
mode = "stream-one"

# ——————————————————————————————————————————————————————————————————

# vless+ws
# [[proxies.vless]]
# remarks_prefix = "④"
# uuid = "0195bf7c-f8c6-7add-aa36-a2145cc38ebb"
# host = "vless1.username.workers.dev"
# server_name = "vless1.username.workers.dev"
# path = "/"
# # random_ports = [80, 8080, 8880, 2052, 2082, 2086, 2095]
# network = "ws"
# mode = ""

# vless+ws+tls
[[proxies.vless]]
remarks_prefix = "⑤"
uuid = "0195bf7d-17d6-704c-bd6b-fa56710382cc"
host = "vless2.pages.dev"
server_name = "vless2.pages.dev"
path = "/"
# random_ports = [443, 2053, 2083, 2087, 2096, 8443]
network = "ws"
mode = ""

# vless+xhttp+tls
[[proxies.vless]]
remarks_prefix = "⑥"
uuid = "0195bf7d-17d6-704c-bd6b-fa56710382cc"
host = "vless-xhttp.pages.dev"
server_name = "vless-xhttp.pages.dev"
path = "/"
# random_ports = [443, 2053, 2083, 2087, 2096, 8443]
network = "xhttp"
mode = "stream-one"

# ——————————————————————————————————————————————————————————————————

# shadowsocks+ws
# [[proxies.ss]]
# remarks_prefix = "⑦"
# password = "none"
# method = "none"
# host = "ss1.username.workers.dev"                                
# path = "/"          
# tls = false                                           # tls = false 意思使用[80, 8080, 8880, 2052, 2082, 2086, 2095]的端口
# random_ports = [80, 8080, 8880, 2052, 2082, 2086, 2095]

# shadowsocks+ws+tls
[[proxies.ss]]
remarks_prefix = "⑧"
password = "none"
method = "none"
host = "ss2.pages.dev"                                  
path = "/"                             
tls = true                                              # tls = true 意思使用[443, 2053, 2083, 2087, 2096, 8443]的端口
# random_ports = [443, 2053, 2083, 2087, 2096, 8443]

# shadowsocks+ws+tls (加密ss)
[[proxies.ss]]
remarks_prefix = "⑨"
password = "wd4EwCx+HxB1EBHaDtU1IA=="
method = "2022-blake3-aes-128-gcm"                      # 默认是none，可以指定 aes-128-gcm、aes-256-gcm、chacha20-ietf-poly1305、2022-blake3-aes-128-gcm、2022-blake3-aes-256-gcm、2022-blake3-chacha20-poly1305
host = "ss3.pages.dev"                                  
path = "/"                             
tls = true
# random_ports = [443, 2053, 2083, 2087, 2096, 8443]

# ——————————————————————————————————————————————————————————————————

# vmess+zero+ws
[[proxies.vmess]]
remarks_prefix = "⑩"
uuid = "0195bf7c-f8c6-7add-aa36-a2145cc38ebb"
host = "vmess.xxxxx.com"                                # 自动判端host域名是否为wokers.dev而开启或关闭tls
server_name = "vmess.xxxxx.com"
path = "/"
# random_ports = [443, 2053, 2083, 2087, 2096, 8443]
network = "ws"
mode = ""

# vmess+zero+xhttp+tls
[[proxies.vmess]]
remarks_prefix = "⑪"
uuid = "0195bf7c-f8c6-7add-aa36-a2145cc38ebb"
host = "vmess-xhttp.xxxxx.com"
server_name = "vmess-xhttp.xxxxx.com"
path = "/"
# random_ports = [443, 2053, 2083, 2087, 2096, 8443]
network = "xhttp"
mode = "stream-one"

# ——————————————————————————————————————————————————————————————————
# ECH仅用于v2ray的vless和trojan分享链接

[ech]
enble_ech = false # 启用/禁用
doh = "https://cloudflare-dns.com/dns-query"
ech_domain = "cloudflare-ech.com"
# 可以通过订阅url的target=v2ray&fetch_ech=true 参数在线获取ECH参数值，短期覆盖下面字段值(并非永远有效)
ech_config_list = "cloudflare-ech.com+https://dns.alidns.com/dns-query"

# ——————————————————————————————————————————————————————————————————

# 后面可以继续复制对应的[[proxies.???]]添加
# 推荐：使用trojan、vless、shadowsocks、vmess顺序排序，可以在url中，传入id=1参数来定位，使用哪个配置
# 注意：
#   1、前面的配置，选择性使用，你有对应的节点才添加，非TLS的（注释掉的[[proxies.???]]），建议不要添加了
#   2、这里配置的random_ports，如果配置不对，可能强制使用这里的端口，导致以为代码选择不对的端口，自我怀疑
#   3、如果ech的enble_ech启用，端口一定要使用443系端口的，如果因random_ports而使用80系端口，会导致节点无法使用

# 本配置文件注释太多，可以通过下面任意一组网站，先复制本toml文件的内容转换为yaml/json，最后转换为toml，清除注释内容
# https://it-tools.tech/toml-to-yaml ==> https://it-tools.tech/yaml-to-toml
# https://ip125.com/tools/toml-to-yaml ==> https://ip125.com/tools/yaml-to-toml
# https://ip125.com/tools/toml-to-json ==> https://ip125.com/tools/json-to-toml